logging:
  file: log/gazpar2haws.log
  console: true
  level: debug
  format: "%(asctime)s %(levelname)s [%(name)s] %(message)s"

${GRDF_CONFIG}

homeassistant:
  host: "${HOMEASSISTANT_HOST}"
  port: "${HOMEASSISTANT_PORT}"
  endpoint: "${HOMEASSISTANT_ENDPOINT}"
  token: "${HOMEASSISTANT_TOKEN}"
