---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.23"
  amd64: "ghcr.io/home-assistant/amd64-base:3.23"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Gazpar2HAWS add-on"
  org.opencontainers.image.description: "Gateway that reads data history from the GrDF (French gas provider) meter and send it to Home Assistant energy dashboard"
  org.opencontainers.image.source: "https://github.com/ssenart/gazpar2haws"
  org.opencontainers.image.licenses: "MIT"
args:
  GAZPAR2HAWS_VERSION: "0.5.0a6"
