---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.13-debian12
  amd64: ghcr.io/home-assistant/amd64-base-python:3.13-debian12
  armhf: ghcr.io/home-assistant/armhf-base-python:3.13-debian12
  armv7: ghcr.io/home-assistant/armv7-base-python:3.13-debian12
  i386: ghcr.io/home-assistant/i386-base-python:3.13-debian12
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Gazpar2HAWS add-on"
  org.opencontainers.image.description: "Gateway that reads data history from the GrDF (French gas provider) meter and send it to Home Assistant energy dashboard"
  org.opencontainers.image.source: "https://github.com/ssenart/gazpar2haws"
  org.opencontainers.image.licenses: "MIT"
args:
  GAZPAR2HAWS_VERSION: "0.5.0a2"
