name: 'publish-to-testpypi'
description: 'Publish the artifact to TestPyPI'
inputs:
  package-name:
    description: "Package name to publish available in the actions workspace"
    required: true
  action_ref:
    default: ${{ github.action_ref }}
  action_repo:
      default: ${{ github.action_repo }}
  action_repo-id:
      default: ${{ github.action_repo-id }}                

  environment:
    name: testpypi
    url: https://test.pypi.org/p/gazpar2haws

  permissions:
    id-token: write  # IMPORTANT: mandatory for trusted publishing

runs:
  using: "composite"    
  steps:
  #----------------------------------------------
  # Workaround to get the REF, REPO and REPO_ID (see https://github.com/actions/runner/issues/2473).
  - run: echo REF=$REF
    env:
      REF: release/v1
    shell: bash    
  - run: echo REPO=$REPO
    env:
      REPO: pypa/gh-action-pypi-publish
    shell: bash
  - run: echo REPO_ID=$REPO_ID
    env:
      REPO_ID: 904401178
    shell: bash
  - run: |
    echo "ref=$REF" >>"$GITHUB_OUTPUT"
    echo "repo=$REPO" >>"$GITHUB_OUTPUT"
    echo "repo-id=$REPO_ID" >>"$GITHUB_OUTPUT"
  #----------------------------------------------
    
  - name: Download the package
    uses: actions/download-artifact@v4
    with:
      name: ${{ inputs.package-name }}
      path: dist/
  - name: Publish 📦 to TestPyPI
    uses: pypa/gh-action-pypi-publish@release/v1
    with:
      repository-url: https://test.pypi.org/legacy/
      verbose: true
