name: 'publish-to-testpypi'
description: 'Publish the artifact to TestPyPI'
inputs:
  package-name:
    description: "Package name to publish available in the actions workspace"
    required: true

environment:
    name: testpypi
    url: https://test.pypi.org/p/${{ inputs.package-name }}

permissions:
    id-token: write  # IMPORTANT: mandatory for trusted publishing

runs:
  using: "composite"
  steps:
  - name: Download all the dists
    uses: actions/download-artifact@v4
    with:
      name: ${{ inputs.package-name }}
      path: dist/
  - name: Publish 📦 to TestPyPI
    uses: pypa/gh-action-pypi-publish@release/v1
    with:
      repository-url: https://test.pypi.org/legacy/
      verbose: true
