name: "publish-to-dockerhub"
description: "Publish to DockerHub workflow"

inputs:
  image:
    description: "Docker image name"
    required: true
  version:
    description: "Version of the image"
    required: true
  username:
    description: "DockerHub username"
    required: true
  password:
    description: "DockerHub password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image }}
        tags: |
          # Set latest tag for the default branch
          type=raw,value=latest,enable={{is_default_branch}}
          # Set the version tag for all branches
          type=raw,value=${{ inputs.version }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}"
        file: ./docker/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
