name: 'publish-to-pypi'
description: 'Publish the artifact to PyPI'
inputs:
  package-name:
    description: "Package name to publish available in the actions workspace"
    required: true

environment:
    name: pypi
    url: https://pypi.org/p/${{ inputs.package-name }}

permissions:
    id-token: write  # IMPORTANT: mandatory for trusted publishing

runs:
  using: "composite"
  steps:
  - name: Download all the dists
    uses: actions/download-artifact@v4
    with:
      name: ${{ inputs.package-name }}
      path: dist/
  - name: Publish 📦 to PyPI
    uses: pypa/gh-action-pypi-publish@release/v1
    with:
      verbose: true
