name: 'python-lint'
description: 'Python linting workflow'

inputs:
  python-version:
    description: 'Python version'
    required: true
    default: '3.13'

runs:
  using: "composite"
  steps:
    #----------------------------------------------
    #  Set-up python
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}    

    #----------------------------------------------
    #  Load pip cache if cache exists
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
        restore-keys: ${{ runner.os }}-pip

    #----------------------------------------------
    #  Install linters
    - name: Install linters
      shell: bash
      run: python -m pip install pylint flake8 black isort mypy ruff

    #----------------------------------------------
    #  Run linters    
    - name: Run linters
      shell: bash
      run: |
        pylint . --disable=logging-fstring-interpolation
        flake8 .
        black . --check
        isort . --check-only
        mypy .
        ruff check .
