name: CI
run-name: "${{ github.event_name == 'workflow_dispatch' && format('CI: {0}', github.ref_name) || '' }}"

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - feature/*
  pull_request: ~
  workflow_dispatch:
    inputs:
      skip-lint:
        description: 'Skip linting'
        required: false
        default: false
        type: boolean
      skip-tests:
        description: 'Skip tests'
        required: false
        default: false
        type: boolean

env:
  DEFAULT_PYTHON_VERSION: "3.12"
  TARGET_PYTHON_VERSIONS: "[ '3.9', '3.10', '3.11', '3.12', '3.13' ]"

jobs:
  #----------------------------------------------
  # Collect information
  information:
    name: Collect information
    outputs:
      package-version: ${{ steps.compute-version.outputs.pep440-version }}
      semantic-version: ${{ steps.compute-version.outputs.semantic-version }}
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      # Display Github environment variables
      - name: Display Github environment variables
        run: printenv | grep '^GITHUB_' | sort

      #----------------------------------------------
      # Check-out repo
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      #----------------------------------------------
      # Compute the version of the project based in the current checkout branch
      - name: Compute version
        id: compute-version
        uses: ./.github/workflows/compute-version

      #----------------------------------------------
      # Display versions
      - name: Display versions
        run: |
          echo "package-version=${{ steps.compute-version.outputs.pep440-version }}"
          echo "semantic-version=${{ steps.compute-version.outputs.semantic-version }}"

  #----------------------------------------------
  # Lint
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #  Check-out repo
      - name: Check out repository
        uses: actions/checkout@v4

      #----------------------------------------------
      # Linting the code
      - name: Lint
        uses: ./.github/workflows/python-lint
        with:
          python-version: ${DEFAULT_PYTHON_VERSION}

  #----------------------------------------------
  # Test
  test:
    name: Test
    strategy:
      fail-fast: true
      matrix:
        python-version: ${TARGET_PYTHON_VERSIONS}
    runs-on: "ubuntu-latest"
    steps:
      #----------------------------------------------
      #  Check-out repo
      - name: Check out repository
        uses: actions/checkout@v4
      #----------------------------------------------
      # Testing the code
      - name: Testing
        uses: ./.github/workflows/python-test
        with:
          python-version: ${{ matrix.python-version }}    