name: Test Python Testing

on: workflow_dispatch

permissions:
  contents: read # Allow to commit and push.

jobs:

  #----------------------------------------------
  # Testing
  testing:
    name: Testing

    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
    runs-on: ${{ matrix.os }}

    steps:
      #----------------------------------------------
      #  Check-out repo
      - name: Check out repository
        uses: actions/checkout@v4

      #----------------------------------------------
      # Testing the code
      - name: Testing
        uses: ./.github/workflows/python-test
        with:
          python-version: ${{ matrix.python-version }}            