name: Test Python Linting

on: push

permissions:
  contents: read # Allow to commit and push.

jobs:

  #----------------------------------------------
  # Linting
  linting:
    name: Linting

    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
    runs-on: ${{ matrix.os }}

    steps:
      #----------------------------------------------
      #  Check-out repo
      - name: Check out repository
        uses: actions/checkout@v4

      #----------------------------------------------
      # Linting the code
      - name: Linting
        uses: ./.github/workflows/python-lint
            